### PR TITLE
Design layout

### PR DESCRIPTION
**Pull request by ohaddahan**
# Description

Design layout, improved configurability (still need some extra loving).

## Type of change

- [x] New feature
- [x] Refactor

## How Has This Been Tested?

- [x] Manual test (need more)

### CODE REVIEW

**Comment by levicook** [comment]
This looks _very extensive_ and makes me worry that it's getting too far from the goals of the project. This is meant to be a fork and customize starter app & it's supposed to start off looking a bit rough.

If you think this enables that please attach screeshots or a loom video showing how that's accomplished.

**Comment by GonRogue** [comment]
Hi, after I followed all of the steps, I got this error, when I tried to run the command "yarn start".
./src/pages/home.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/pages/home.scss)
Cannot find module 'sass'

**Comment by ohaddahan** [comment]
> This looks _very extensive_ and makes me worry that it's getting too far from the goals of the project. This is meant to be a fork and customize starter app & it's supposed to start off looking a bit rough.
> 
> If you think this enables that please attach screeshots or a loom video showing how that's accomplished.

Loom video : https://www.loom.com/share/168ca969111f460cac644d635b73b85a

I agree it might be a big change, it's supposed to help kick start even faster.
Maybe it should just be a fork, and https://github.com/exiled-apes/candy-machine-mint/pull/39 also.
With the main README pointing to them as an option.

The only thing we need from the main repo is to to keep similar structure to https://github.com/Realtyka/real-commons/pull/79 , that way there will be no crazy syncs.

What do you think, better go that route?

**Comment by ohaddahan** [comment]
> Cannot find module 'sass'

I think this should work https://github.com/laravel-mix/laravel-mix/issues/2103

**Comment by GonRogue** [comment]
Hello guys, can you show me the way to change the connect and mint button,  I tried to change the Navbar.scss but it just added a layer on top of the existing background of the button.  I tried to style it in the ConnectionMintButton.tsx but It didn't work out.

**Comment by ohaddahan** [comment]
> Hello guys, can you show me the way to change the connect and mint button, I tried to change the Navbar.scss but it just added a layer on top of the existing background of the button. I tried to style it in the ConnectionMintButton.tsx but It didn't work out.

can you post what you tried?

**Comment by ohaddahan** [comment]
Closing, will keep it as a separate fork as @levicook mentioned, it might be too big of a change.

**Pull request closed without merging**
